name: rollstones.github.io TO rollstones.github.io:GH_PAGES
#指定推送master分支时执行
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: "14.x"

jobs:
  build-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: use action-npm-install
        uses: Jaid/action-npm-install@v1.2.4
      - name: install and Build
        run: |
          yarn install
          yarn run build
      - name: CNAME
        run: echo 'www.rollstones.cn' > docs/.vuepress/dist/CNAME
      - name: Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_DIR: docs/.vuepress/dist/
